apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: yugabyte-scc
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny