---
# Create namespace for the deployment
apiVersion: v1
kind: Namespace
metadata:
  name: edb-keycloak
---
# Create a Secret for pulling images from EDB registry
apiVersion: v1
kind: Secret
metadata:
  name: edb-registry-secret
  namespace: edb-keycloak
type: kubernetes.io/dockerconfigjson
data:
  # Replace with your actual EDB registry credentials (base64 encoded)
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5lbnRlcnByaXNlZGIuY29tIjp7InVzZXJuYW1lIjoiWU9VUl9VU0VSTkFNRSIsInBhc3N3b3JkIjoiWU9VUl9QQVNTV09SRCIsImF1dGgiOiJXVTlWVWw5VlUwVlNUa0ZOUlRwWlQxVlNYMUJCVTFOWFQxSkUifX19
---
# Create a ServiceAccount that uses the registry secret
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edb-ai-serviceaccount
  namespace: edb-keycloak
imagePullSecrets:
  - name: edb-registry-secret
---
# Create a Secret for PostgreSQL admin credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-ai-admin
  namespace: edb-keycloak
type: Opaque
data:
  # Password is 'postgres' encoded in base64
  password: cG9zdGdyZXM=
---
# Create a Secret for the Keycloak database user password
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: edb-keycloak
type: Opaque
data:
  # Password is 'keycloak' encoded in base64
  password: a2V5Y2xvYWs=
---
# Create Portworx StorageClass for PostgreSQL data
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-postgres-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  io_profile: "db"
  io_priority: "high"
---
# Create Portworx StorageClass for backups
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-backup-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: "sequential"
  io_priority: "medium"
---
# Create a Secret for Portworx backup credentials
apiVersion: v1
kind: Secret
metadata:
  name: px-backup-creds
  namespace: edb-keycloak
type: Opaque
data:
  # Replace with your actual credentials (base64 encoded)
  accessKeyId: WU9VUl9BQ0NFU1NfS0VZ
  secretAccessKey: WU9VUl9TRUNSRVRfS0VZ
---
# Deploy EDB Postgres AI cluster with replicas
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres-ai
  namespace: edb-keycloak
  labels:
    app: keycloak-postgres-ai
spec:
  instances: 3  # Primary + 2 replicas
  
  # Use EDB Postgres AI image
  imageName: registry.enterprisedb.com/edb-postgres-ai:15.4.0
  imagePullSecrets:
    - name: edb-registry-secret
  
  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "512MB"
      # AI extension parameters
      pgvector.dimension: "1536"  # For OpenAI embeddings
      
  # Storage configuration
  storage:
    size: 20Gi
    storageClass: px-postgres-sc  # Using Portworx storage class
  
  # Bootstrap superuser credentials
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: postgres-ai-admin
  
  # Resources for AI workloads
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"
  
  # Replica configuration
  replicationSlots:
    highAvailability:
      enabled: true
  
  # OpenShift specific configurations
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
  
  # Security context for OpenShift
  primaryUpdateStrategy: unsupervised
  
  # Monitoring configuration
  monitoring:
    enablePodMonitor: true
  
  # Backup configuration using Portworx
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://px-backup/keycloak-postgres-ai
      endpointURL: https://px-backup-service.portworx.svc.cluster.local
      s3Credentials:
        accessKeyId:
          name: px-backup-creds
          key: accessKeyId
        secretAccessKey:
          name: px-backup-creds
          key: secretAccessKey
      wal:
        compression: snappy
        maxParallel: 8
      data:
        compression: snappy
        immediateCheckpoint: true
        jobs: 4
---
# Create the Keycloak database
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: PostgresqlDatabase
metadata:
  name: keycloak-db
  namespace: edb-keycloak
spec:
  cluster:
    name: keycloak-postgres-ai
  database: keycloak
  owner: keycloak
---
# Create the Keycloak user
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: PostgresqlUser
metadata:
  name: keycloak-user
  namespace: edb-keycloak
spec:
  cluster:
    name: keycloak-postgres-ai
  name: keycloak
  password:
    secretName: keycloak-db-credentials
    secretKey: password
  login: true
  options:
    - CREATEDB
    - NOSUPERUSER
---
# Post-initialization script to enable AI extensions
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-ai-init
  namespace: edb-keycloak
spec:
  template:
    spec:
      serviceAccountName: edb-ai-serviceaccount
      containers:
      - name: postgres-client
        image: registry.enterprisedb.com/edb-postgres-client:15
        command:
        - /bin/bash
        - -c
        - |
          PGPASSWORD=$(cat /etc/postgres-password/password) psql -h keycloak-postgres-ai-rw -U postgres -d postgres -c "CREATE EXTENSION IF NOT EXISTS pgvector; CREATE EXTENSION IF NOT EXISTS pg_embedding; CREATE EXTENSION IF NOT EXISTS pg_vectorize;"
          PGPASSWORD=$(cat /etc/postgres-password/password) psql -h keycloak-postgres-ai-rw -U postgres -d keycloak -c "CREATE EXTENSION IF NOT EXISTS pgvector; CREATE EXTENSION IF NOT EXISTS pg_embedding; CREATE EXTENSION IF NOT EXISTS pg_vectorize;"
        volumeMounts:
        - name: postgres-password
          mountPath: /etc/postgres-password
      volumes:
      - name: postgres-password
        secret:
          secretName: postgres-ai-admin
      restartPolicy: OnFailure
---
# Create a scheduled backup job using Portworx
apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: keycloak-postgres-backup-policy
  namespace: edb-keycloak
spec:
  interval:
    intervalMinutes: 1440  # Daily backup
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: BackupLocation
metadata:
  name: px-backup-location
  namespace: edb-keycloak
spec:
  type: s3
  s3Config:
    region: us-east-1
    accessKeyID: YOUR_ACCESS_KEY
    secretAccessKey: YOUR_SECRET_KEY
    endpoint: https://px-backup-service.portworx.svc.cluster.local
    bucket: px-backup
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackupSchedule
metadata:
  name: keycloak-postgres-backup-schedule
  namespace: edb-keycloak
spec:
  schedulePolicyName: keycloak-postgres-backup-policy
  template:
    spec:
      backupLocation: px-backup-location
      namespaces:
        - edb-keycloak
      selectors:
        app: keycloak-postgres-ai
---
# Create an additional Service for external access to the database
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-external
  namespace: edb-keycloak
  labels:
    app: keycloak-postgres-ai
spec:
  selector:
    postgresql: keycloak-postgres-ai
    role: primary
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
# Create a Service for admin access to the database
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-admin
  namespace: edb-keycloak
  labels:
    app: keycloak-postgres-ai
    role: admin-access
spec:
  selector:
    postgresql: keycloak-postgres-ai
    role: primary
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
# Create a Route for secure external access to the admin service
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak-postgres-admin-route
  namespace: edb-keycloak
  labels:
    app: keycloak-postgres-ai
  annotations:
    description: "Route for PostgreSQL admin access"
spec:
  to:
    kind: Service
    name: keycloak-postgres-admin
    weight: 100
  port:
    targetPort: postgres
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
---
# Create a Route for secure external access to the database
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak-postgres-route
  namespace: edb-keycloak
  labels:
    app: keycloak-postgres-ai
  annotations:
    description: "Route for PostgreSQL database access"
spec:
  to:
    kind: Service
    name: keycloak-postgres-external
    weight: 100
  port:
    targetPort: postgres
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
---
# Create a ConfigMap for database connection information
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-postgres-connection-info
  namespace: edb-keycloak
data:
  README.md: |
    # EDB Postgres AI for Keycloak Connection Information
    
    ## Internal Connection (for applications within the cluster)
    - Host: keycloak-postgres-ai-rw.edb-keycloak.svc.cluster.local
    - Port: 5432
    - Database: keycloak
    - Username: keycloak
    - Password: keycloak (stored in Secret: keycloak-db-credentials)
    
    ## External Connection (via OpenShift Route)
    - Host: keycloak-postgres-route-edb-keycloak.apps.your-cluster-domain.com
    - Port: 5432
    - Database: keycloak
    - Username: keycloak
    - Password: keycloak (stored in Secret: keycloak-db-credentials)
    
    ## Admin Connection (via OpenShift Route)
    - Host: keycloak-postgres-admin-route-edb-keycloak.apps.your-cluster-domain.com
    - Port: 5432
    - Database: postgres
    - Username: postgres
    - Password: postgres (stored in Secret: postgres-ai-admin)
